version: '3.9'

services:
  backend:
    container_name: taco-backend
    image: 'taco-cloud:latest'
    restart: always
    ports:
      - '8080:8080'
    env_file:
          - ./.env
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile


  postgres:
    image: postgres:14.10
    container_name: taco-postgres
    restart: unless-stopped
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_URL}
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - ./../tacro-postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: taco-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./../tacro-nginx-logs:/logs

volumes:
  conf:
  vhost:
  html:
  cache:
    driver: local

networks:
  default:
    name: nginx-proxy
    external: true