spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /data-api
  kafka:
    bootstrap-servers:
      - localhost:9092


